//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saduApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public string siparisId { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public string UyeId { get; set; }
        public string UrunId { get; set; }
        public string Adres { get; set; }
        public decimal Fiyat { get; set; }
        public string OdemeId { get; set; }
        public string KargoId { get; set; }
        public Nullable<decimal> KargoUcreti { get; set; }
        public string SiparisDurumuId { get; set; }
        public string TedarikUyeId { get; set; }
    
        public virtual Kargo Kargo { get; set; }
        public virtual OdemeTuru OdemeTuru { get; set; }
        public virtual SiparisDurumu SiparisDurumu { get; set; }
        public virtual Urunler Urunler { get; set; }
        public virtual Uye Uye { get; set; }
        public virtual Uye Uye1 { get; set; }
    }
}
